### ISSUE TITLE
Add a LICENSE file?

### ISSUE THREAD

**Issue by javiertoledo** [ChaxiraxiCabrera/BooksMy#1]
Hi @ChaxiraxiCabrera, nice project! Could you please add a LICENSE file so the people out there knows how they can use your code? If you're not sure about which one to pick, there's this github help page on the topic: https://help.github.com/articles/licensing-a-repository/

Thanks!!

**Comment by ChaxiraxiCabrera** [comment]
Hi @javiertoledo, I just added the LICENSE.md file.
Thanks for the suggestion and documentation!

**Comment by javiertoledo** [comment]
Thanks! Nice choice BTW 💯
